version: '3.8'
services:
  dev:
    build: .devcontainer
    command: sh -c "tail -f /dev/null"
    working_dir: /src
    volumes:
      - ./:/src:delegated
      - /src/node_modules
      - /src/dist
      - /root/.yarn/berry/cache
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/ssh
    ports:
      - '127.0.0.1:4200:4200'
    network_mode: host
